/**
 * Form validation utilities for Ant Design + Zod
 * 
 * ⚠️ AUTO-GENERATED by Omnify - DO NOT EDIT
 * This file is overwritten on every `npx omnify generate`
 * 
 * Compatible with Zod v4.x
 */

import type { RuleObject } from 'antd/es/form';
import type { z } from 'zod';
import { getZodMessage } from './zod-i18n';

/**
 * Convert Zod schema to Ant Design Form rule with i18n support
 *
 * @example
 * // Set locale once at component level
 * setZodLocale('ja');
 *
 * // Use without passing locale
 * <Form.Item
 *   name="email"
 *   rules={[zodRule(customerSchemas.email, 'メールアドレス')]}
 * >
 *   <Input />
 * </Form.Item>
 */
export function zodRule<T extends z.ZodTypeAny>(
  schema: T,
  displayName?: string
): RuleObject {
  const field = displayName ?? 'この項目';

  return {
    validator: async (_, value) => {
      // 空チェック - 必須として扱う
      if (value === undefined || value === null || value === '') {
        if (schema.safeParse(undefined).success) return;
        throw new Error(getZodMessage('required', { displayName: field }));
      }

      const result = schema.safeParse(value);
      if (result.success) return;

      // 最初のZodエラーを取得
      const issue = result.error.issues[0];
      if (!issue) {
        throw new Error(getZodMessage('required', { displayName: field }));
      }

      // エラータイプに基づいて翻訳（Zod v4対応）
      const issueAny = issue as unknown as Record<string, unknown>;
      switch (issue.code) {
        case 'too_small': {
          const origin = issueAny.origin as string | undefined;
          const minimum = issueAny.minimum as number;
          if (origin === 'string' && minimum === 1) {
            throw new Error(getZodMessage('required', { displayName: field }));
          }
          if (origin === 'string') {
            throw new Error(getZodMessage('minLength', { displayName: field, min: minimum }));
          }
          throw new Error(getZodMessage('min', { displayName: field, min: minimum }));
        }

        case 'too_big': {
          const origin = issueAny.origin as string | undefined;
          const maximum = issueAny.maximum as number;
          if (origin === 'string') {
            throw new Error(getZodMessage('maxLength', { displayName: field, max: maximum }));
          }
          throw new Error(getZodMessage('max', { displayName: field, max: maximum }));
        }

        // Zod v4: 'invalid_string' → 'invalid_format'
        case 'invalid_format': {
          const format = issueAny.format as string | undefined;
          if (format === 'email') {
            throw new Error(getZodMessage('email', { displayName: field }));
          }
          if (format === 'url') {
            throw new Error(getZodMessage('url', { displayName: field }));
          }
          if (format === 'regex') {
            throw new Error(getZodMessage('pattern', { displayName: field }));
          }
          break;
        }

        case 'invalid_type': {
          const expected = issueAny.expected as string | undefined;
          // Zod v4: チェックはexpectedフィールドを使用
          if (expected && value === undefined) {
            throw new Error(getZodMessage('required', { displayName: field }));
          }
          break;
        }
      }

      // フォールバック: Zodのオリジナルメッセージを使用
      throw new Error(issue.message);
    },
  };
}

/**
 * Create required rule with i18n message
 *
 * @example
 * <Form.Item
 *   name="name"
 *   rules={[requiredRule('名前')]}
 * >
 *   <Input />
 * </Form.Item>
 */
export function requiredRule(displayName: string): RuleObject {
  return {
    required: true,
    message: getZodMessage('required', { displayName }),
  };
}
