/**
 * useFormMutation - Form mutation with auto Laravel error handling
 * 
 * ⚠️ AUTO-GENERATED by Omnify - DO NOT EDIT
 * This file is overwritten on every `npx omnify generate`
 *
 * @example
 * const mutation = useFormMutation({
 *   form,
 *   mutationFn: (data) => axios.post('/api/customers', data),
 *   invalidateKeys: [['customers']],
 *   successMessage: '保存しました',
 * });
 *
 * <Form form={form} onFinish={mutation.mutate}>
 *   ...
 *   <Button loading={mutation.isPending}>保存</Button>
 * </Form>
 */

import { useMutation, useQueryClient } from '@tanstack/react-query';
import { App } from 'antd';
import type { FormInstance } from 'antd';

// =============================================================================
// Types
// =============================================================================

interface UseFormMutationOptions<TData, TResult> {
  /** Ant Design form instance */
  form: FormInstance;
  /** API call function */
  mutationFn: (data: TData) => Promise<TResult>;
  /** Query keys to invalidate on success */
  invalidateKeys?: readonly (readonly unknown[])[];
  /** Success message to show */
  successMessage?: string;
  /** Callback on success */
  onSuccess?: (data: TResult) => void;
  /** Callback on error */
  onError?: (error: unknown) => void;
}

// =============================================================================
// Laravel Error Helpers
// =============================================================================

/**
 * Parse Laravel validation errors to Ant Design form format
 */
function getFormErrors(error: unknown): { name: string; errors: string[] }[] {
  const data = (error as any)?.response?.data;
  const errors = data?.errors;

  if (!errors || typeof errors !== 'object') return [];

  return Object.entries(errors).map(([name, messages]) => ({
    name,
    errors: Array.isArray(messages) ? messages : [String(messages)],
  }));
}

/**
 * Get general validation message from Laravel response
 */
function getValidationMessage(error: unknown): string | null {
  const data = (error as any)?.response?.data;
  return data?.message || null;
}

// =============================================================================
// Hook
// =============================================================================

export function useFormMutation<TData, TResult = unknown>({
  form,
  mutationFn,
  invalidateKeys = [],
  successMessage,
  onSuccess,
  onError,
}: UseFormMutationOptions<TData, TResult>) {
  const queryClient = useQueryClient();
  const { message } = App.useApp();

  return useMutation({
    mutationFn,
    onSuccess: (data) => {
      // Invalidate queries
      invalidateKeys.forEach((key) => {
        queryClient.invalidateQueries({ queryKey: [...key] });
      });

      // Show success message
      if (successMessage) {
        message.success(successMessage);
      }

      // Custom callback
      onSuccess?.(data);
    },
    onError: (error) => {
      // Set form field errors from Laravel validation
      const formErrors = getFormErrors(error);
      if (formErrors.length > 0) {
        form.setFields(formErrors);
      }

      // Show general error message
      const validationMessage = getValidationMessage(error);
      if (validationMessage) {
        message.error(validationMessage);
      }

      // Custom callback
      onError?.(error);
    },
  });
}
